# Generated by Django 6.0.4 on 2026-05-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0014_en_numeric_collation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopusage',
            name='line_name',
            field=models.CharField(db_collation='en_numeric'),
        ),
    ]
