# Generated by Django 6.0.6 on 2026-06-12 17:00

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0015_alter_stopusage_line_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
    ]
