# Generated by Django 6.0.4 on 2026-04-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0013_stoppoint_description_stoppoint_notes_and_more'),
        ('bustimes', '0013_route_timezone_alter_timetabledatasource_search'),
        ('vosa', '0002_alter_licence_authorised_discs_alter_licence_discs'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['calendar', 'operation', 'special'], name='bustimes_ca_calenda_0f123c_idx'),
        ),
        migrations.AddIndex(
            model_name='calendardate',
            index=models.Index(fields=['calendar', 'start_date', 'end_date', 'operation'], name='bustimes_ca_calenda_e1027c_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(condition=models.Q(('service__isnull', False)), fields=['source', 'service_code'], name='route_source_service_code'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(condition=models.Q(('pick_up', True)), fields=['stop', 'departure'], include=('trip',), name='stoptime_stop_dep_covering'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['trip', 'id'], name='stoptime_trip_id'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['source', 'start_date', 'end_date'], name='bustimes_ve_source__8a8cdc_idx'),
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='bustimes_ro_source__a99810_idx',
        ),
        migrations.RemoveIndex(
            model_name='stoptime',
            name='bustimes_st_stop_id_cde000_idx',
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='operation',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendardate',
            name='start_date',
            field=models.DateField(),
        ),
    ]
