# Generated by Django 6.0.4 on 2026-04-19 17:42

from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('busstops', '0013_stoppoint_description_stoppoint_notes_and_more'),
        ('bustimes', '0014_remove_route_bustimes_ro_source__a99810_idx_and_more'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name='stoptime',
            index=models.Index(
                condition=models.Q(('pick_up', True)),
                fields=['stop', 'departure'],
                include=('trip',),
                name='stoptime_stop_dep_covering',
            ),
        ),
        AddIndexConcurrently(
            model_name='stoptime',
            index=models.Index(
                fields=['trip', 'id'],
                name='stoptime_trip_id',
            ),
        ),
        RemoveIndexConcurrently(
            model_name='stoptime',
            name='bustimes_st_stop_id_cde000_idx',
        ),
    ]
