# Generated by Django 6.0.4 on 2026-05-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0014_en_numeric_collation'),
        ('bustimes', '0015_remove_stoptime_bustimes_st_stop_id_cde000_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='line_name',
            field=models.CharField(blank=True, db_collation='en_numeric', max_length=255),
        ),
    ]
