# Generated by Django 6.0.5 on 2026-05-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busstops', '0015_alter_stopusage_line_name'),
        ('bustimes', '0016_alter_route_line_name'),
        ('vehicles', '0020_vehiclecode_unique_vehicle_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(fields=['service', '-id'], name='vehiclejourney_service_id'),
        ),
        migrations.AddIndex(
            model_name='vehiclejourney',
            index=models.Index(fields=['vehicle', '-id'], name='vehiclejourney_vehicle_id_desc'),
        ),
    ]
