# Generated by Django 6.0.5 on 2026-05-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_vehiclejourney_service_vehicle_id_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fleet_code',
            field=models.CharField(blank=True, db_collation='en_numeric', max_length=24),
        ),
    ]
