name: Run tests

on:
  push:
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '20'
        cache: 'npm'

    - run: npm install-ci-test
    - run: npm run lint
    - run: npm run build

  test-backend:
    runs-on: ubuntu-24.04
    timeout-minutes: 8
    container:
      image: ghcr.io/bustimes/bustimes.org/bustimes-base:3.14

    permissions:
      packages: read  # to use the bustimes-base docker image

    services:
      postgres:
        image: postgis/postgis:18-3.6

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_INITDB_ARGS: "--no-sync"
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 3s
          --health-retries 5
          --health-start-period 5s
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

    - run: uv sync --group test --frozen && mkdir staticfiles

    - name: run tests
      env:
        DATABASE_URL: postgis://postgres:postgres@postgres/postgres
        SECRET_KEY: secret
      run: uv run coverage run --parallel-mode --concurrency=multiprocessing ./manage.py test --parallel=2 --keepdb --durations 10

    - name: generate coverage HTML report
      run: |
        uv run coverage combine
        uv run coverage html

    - name: upload coverage HTML artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: coverage-html
        path: htmlcov

  publish-coverage:
    needs: test-backend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    concurrency:
      group: pages
      cancel-in-progress: false

    steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: coverage-html
        path: htmlcov

    - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

    - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      with:
        path: htmlcov

    - id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
